node {

    stage('Initialize'){
        def dockerHome = tool 'myDocker'
        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }

    stage('Checkout') {
        checkout scm
    }

    stage("Remove App containers"){
        sh "docker-compose down"
    }

    stage('Run App'){
        sh "docker-compose up"
        echo "App running on port 80"
    }

}
