node {

    stage('Checkout') {
        checkout scm
    }

    stage("Remove App containers"){
        sh "docker-compose down"
    }

    stage('Run App'){
        sh "docker-compose up"
        echo "App running on port 80"
    }

}
